---
title: "blog1"
author: "Feven Yohannes"
date: "September 9, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(maps)
library(cowplot)
library(tidyverse)

```


```{r, Downloading data}

 # Readig in data 1

popvote_bystander <- read_csv("popvote_bystate_1948-2016.csv",col_types = cols(
  state = col_character(),
  year = col_double(),
  total = col_double(),
  D = col_double(),
  R = col_double(),
  R_pv2p = col_double(),
  D_pv2p = col_double()
))

 # Reading in data 2

popvote <- read_csv("popvote_1948-2016.csv",col_types = cols(
  year = col_double(),
  party = col_character(),
  winner = col_logical(),
  candidate = col_character(),
  pv = col_double(),
  pv2p = col_double(),
  incumbent = col_logical(),
  incumbent_party = col_logical(),
  prev_admin = col_logical()
))
```

```{r, Graph 1}

# Making the dataframe wider

popvote_wide_df <- popvote %>%
  select(year, party, pv2p) %>%
  spread(party, pv2p)


  # Creating graph 1 dataframe

graph1_df <- popvote_wide_df %>%
  
  # Create new variable to look at vote share difference
  
  mutate(difference = (democrat-republican),absolute_difference =abs(democrat-republican)) %>%

  
  # Mutate to get colors for graph
  
  mutate(Color = ifelse(difference > 0, "blue", "red")) %>%
  
  # Making sure there are no duplicates, while keeping all other variables
  
  distinct(year, .keep_all = TRUE)
  
  
  # Creating Graph 1

  graph1_df %>%
  ggplot(aes(x=year,y=absolute_difference,fill=Color)) +geom_col() +
  labs(title ="Difference in National Popular Vote in Presidential Elections from 1948 to 2016",
        subtitle="Exploring Win Margins by Democrats and Republicans",
    x="Election Year",y= "Difference in Popular Vote (%)",
    caption= "Caption: The election of 2000 and 2016 are instances where the \n candidate won the popular vote, but lost the election") +
  theme(plot.title = element_text(face = "bold",size=11)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party that Won the Popular Vote")
  

```



```{r,Graphic 2}

  # Arizona 

Arizona <- popvote_bystander %>%
  filter(state=="Arizona") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Arizona's Presidential Vote Share 1948-2016",
    x="Election Year",y= "Percentage of Vote Share by Party") +
  theme(axis.title.y = element_text(size=8)) +
  theme(plot.title = element_text(face = "bold",size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))

# Florida

Florida <- popvote_bystander %>%
  filter(state=="Florida") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Florida's Presidential Popular Vote Share 1948-2016",
    x="Election Year",y= "Percentage of Vote Share by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))


# Georgia 

Georgia <- popvote_bystander %>%
  filter(state=="Georgia") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Georgia's Presidential Popular Vote Share 1948-2016",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))


  # Michigan 

Michigan <- popvote_bystander %>%
  filter(state=="Michigan") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Michigan's Presidential Popular Vote Share 1948- 2016",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))


  # Minnesota 

Minnesota <- popvote_bystander %>%
  filter(state=="Minnesota") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Minnnesota's Presidential Popular Vote Share 1948-2016",
        subtitle="Exploring Win Margins by Democrats and Republicans",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))



  # North Carolina 

North_Carolina  <- popvote_bystander %>%
  filter(state=="North Carolina") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="North Carolina's Presidential Popular Vote Share 1948-2016",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8))+
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))



  #Pennsylvania 

Pennsylvania <- popvote_bystander %>%
  filter(state=="Pennsylvania") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Pennsylavnia's Presidental Vote Share 1948-2016",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8))+
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))



  # Wisconsin 

Wisconsin <- popvote_bystander %>%
  filter(state=="Wisconsin") %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Wisconsin's Presidential Popular Vote Share 1948-2016",
        subtitle="Exploring Win Margins by Democrats and Republicans",
    x="Election Year",y= "Percentage of Vote Shares by Party") +
  theme(plot.title = element_text(face = "bold",size=8)) +
  theme(axis.title.y = element_text(size=8)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party")+
  theme(legend.title = element_text(color = "gray1", size = 9.5),legend.key.width = unit(0.4,"cm"),legend.key.size = unit(0.6, "cm"))



plot_grid(Arizona,Florida,Georgia)

plot_grid(Minnesota,Wisconsin,Michigan)

plot_grid(Pennsylvania,North_Carolina)



  
  
```

